// Package maintenance provides test maintenance functionality.
// This file implements the PR creator for submitting test updates.
package maintenance

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"
)

// PRCreatorConfig configures the PR creator
type PRCreatorConfig struct {
	// GitHubToken for authentication
	GitHubToken string
	// BaseURL for GitHub API (for enterprise)
	BaseURL string
	// DryRun if true, doesn't create actual PRs
	DryRun bool
	// BranchPrefix for maintenance branches
	BranchPrefix string
	// AutoMerge if true, enables auto-merge
	AutoMerge bool
	// Labels to add to the PR
	Labels []string
}

// DefaultPRCreatorConfig returns sensible defaults
func DefaultPRCreatorConfig() PRCreatorConfig {
	return PRCreatorConfig{
		BaseURL:      "https://api.github.com",
		DryRun:       false,
		BranchPrefix: "qtest/maintenance",
		AutoMerge:    false,
		Labels:       []string{"qtest", "automated", "test-maintenance"},
	}
}

// PRCreator handles creating PRs for test maintenance
type PRCreator struct {
	config     PRCreatorConfig
	httpClient *http.Client
}

// NewPRCreator creates a new PR creator
func NewPRCreator(config PRCreatorConfig) *PRCreator {
	return &PRCreator{
		config: config,
		httpClient: &http.Client{
			Timeout: 30 * time.Second,
		},
	}
}

// PRRequest represents a request to create a PR
type PRRequest struct {
	Owner       string            `json:"owner"`
	Repo        string            `json:"repo"`
	BaseBranch  string            `json:"base_branch"`
	Title       string            `json:"title"`
	Body        string            `json:"body"`
	Files       []FileChange      `json:"files"`
	Results     []PRResultItem `json:"results,omitempty"`
}

// FileChange represents a file to be changed in the PR
type FileChange struct {
	Path    string `json:"path"`
	Content string `json:"content"`
	Action  string `json:"action"` // "create", "update", "delete"
}

// PRResultItem represents a summary result item for the PR body
type PRResultItem struct {
	Type    string `json:"type"`
	File    string `json:"file"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// PRResponse represents the response from creating a PR
type PRResponse struct {
	Number    int       `json:"number"`
	URL       string    `json:"url"`
	HTMLURL   string    `json:"html_url"`
	State     string    `json:"state"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	Branch    string    `json:"branch"`
	DryRun    bool      `json:"dry_run"`
}

// CreateMaintenancePR creates a PR with test maintenance changes
func (p *PRCreator) CreateMaintenancePR(ctx context.Context, req PRRequest) (*PRResponse, error) {
	if len(req.Files) == 0 {
		return nil, fmt.Errorf("no files to include in PR")
	}

	// Generate branch name
	branchName := p.generateBranchName(req)

	// Generate PR body
	body := p.generatePRBody(req)

	if p.config.DryRun {
		return &PRResponse{
			Number:    0,
			URL:       fmt.Sprintf("https://github.com/%s/%s/pull/0", req.Owner, req.Repo),
			HTMLURL:   fmt.Sprintf("https://github.com/%s/%s/pull/0", req.Owner, req.Repo),
			State:     "dry_run",
			Title:     req.Title,
			CreatedAt: time.Now(),
			Branch:    branchName,
			DryRun:    true,
		}, nil
	}

	// In production, this would:
	// 1. Create a new branch
	// 2. Commit files to the branch
	// 3. Create the PR

	// Create branch
	if err := p.createBranch(ctx, req.Owner, req.Repo, branchName, req.BaseBranch); err != nil {
		return nil, fmt.Errorf("failed to create branch: %w", err)
	}

	// Commit files
	for _, file := range req.Files {
		if err := p.commitFile(ctx, req.Owner, req.Repo, branchName, file); err != nil {
			return nil, fmt.Errorf("failed to commit file %s: %w", file.Path, err)
		}
	}

	// Create PR
	prResp, err := p.createPullRequest(ctx, req.Owner, req.Repo, branchName, req.BaseBranch, req.Title, body)
	if err != nil {
		return nil, fmt.Errorf("failed to create PR: %w", err)
	}

	// Add labels if configured
	if len(p.config.Labels) > 0 {
		_ = p.addLabels(ctx, req.Owner, req.Repo, prResp.Number, p.config.Labels)
	}

	return prResp, nil
}

// generateBranchName creates a unique branch name for the maintenance PR
func (p *PRCreator) generateBranchName(req PRRequest) string {
	timestamp := time.Now().Format("20060102-150405")
	return fmt.Sprintf("%s/%s", p.config.BranchPrefix, timestamp)
}

// generatePRBody creates the PR description
func (p *PRCreator) generatePRBody(req PRRequest) string {
	var sb strings.Builder

	sb.WriteString("## Test Maintenance Update\n\n")
	sb.WriteString("This PR was automatically generated by QTest to maintain test coverage.\n\n")

	// Summary of changes
	var created, updated, deleted int
	for _, f := range req.Files {
		switch f.Action {
		case "create":
			created++
		case "update":
			updated++
		case "delete":
			deleted++
		}
	}

	sb.WriteString("### Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Tests Created:** %d\n", created))
	sb.WriteString(fmt.Sprintf("- **Tests Updated:** %d\n", updated))
	sb.WriteString(fmt.Sprintf("- **Tests Removed:** %d\n", deleted))
	sb.WriteString("\n")

	// List of files changed
	sb.WriteString("### Files Changed\n\n")
	for _, f := range req.Files {
		icon := "📝"
		switch f.Action {
		case "create":
			icon = "✨"
		case "delete":
			icon = "🗑️"
		}
		sb.WriteString(fmt.Sprintf("- %s `%s`\n", icon, f.Path))
	}
	sb.WriteString("\n")

	// Maintenance results if provided
	if len(req.Results) > 0 {
		sb.WriteString("### Maintenance Results\n\n")
		sb.WriteString("| Type | File | Status | Message |\n")
		sb.WriteString("|------|------|--------|--------|\n")
		for _, r := range req.Results {
			status := "✅"
			if !r.Success {
				status = "❌"
			}
			sb.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s |\n", r.Type, r.File, status, r.Message))
		}
		sb.WriteString("\n")
	}

	// Footer
	sb.WriteString("---\n")
	sb.WriteString("🤖 Generated by [QTest](https://github.com/QTest-hq/qtest)\n")

	return sb.String()
}

// createBranch creates a new branch from the base
func (p *PRCreator) createBranch(ctx context.Context, owner, repo, branch, baseBranch string) error {
	// Get base branch SHA
	url := fmt.Sprintf("%s/repos/%s/%s/git/refs/heads/%s", p.config.BaseURL, owner, repo, baseBranch)
	req, err := http.NewRequestWithContext(ctx, "GET", url, nil)
	if err != nil {
		return err
	}
	p.setHeaders(req)

	resp, err := p.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("failed to get base branch: %s", resp.Status)
	}

	var refResp struct {
		Object struct {
			SHA string `json:"sha"`
		} `json:"object"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&refResp); err != nil {
		return err
	}

	// Create new branch
	createURL := fmt.Sprintf("%s/repos/%s/%s/git/refs", p.config.BaseURL, owner, repo)
	createBody := map[string]string{
		"ref": "refs/heads/" + branch,
		"sha": refResp.Object.SHA,
	}
	bodyBytes, _ := json.Marshal(createBody)

	createReq, err := http.NewRequestWithContext(ctx, "POST", createURL, bytes.NewReader(bodyBytes))
	if err != nil {
		return err
	}
	p.setHeaders(createReq)

	createResp, err := p.httpClient.Do(createReq)
	if err != nil {
		return err
	}
	defer createResp.Body.Close()

	if createResp.StatusCode != http.StatusCreated {
		return fmt.Errorf("failed to create branch: %s", createResp.Status)
	}

	return nil
}

// commitFile commits a file to the branch
func (p *PRCreator) commitFile(ctx context.Context, owner, repo, branch string, file FileChange) error {
	url := fmt.Sprintf("%s/repos/%s/%s/contents/%s", p.config.BaseURL, owner, repo, file.Path)

	body := map[string]interface{}{
		"message": fmt.Sprintf("chore(tests): %s %s", file.Action, file.Path),
		"branch":  branch,
	}

	if file.Action == "delete" {
		// Need to get the SHA first
		getReq, _ := http.NewRequestWithContext(ctx, "GET", url+"?ref="+branch, nil)
		p.setHeaders(getReq)
		getResp, err := p.httpClient.Do(getReq)
		if err != nil {
			return err
		}
		defer getResp.Body.Close()

		var fileInfo struct {
			SHA string `json:"sha"`
		}
		json.NewDecoder(getResp.Body).Decode(&fileInfo)
		body["sha"] = fileInfo.SHA
	} else {
		body["content"] = base64Encode(file.Content)
	}

	bodyBytes, _ := json.Marshal(body)
	req, err := http.NewRequestWithContext(ctx, "PUT", url, bytes.NewReader(bodyBytes))
	if err != nil {
		return err
	}
	p.setHeaders(req)

	resp, err := p.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		return fmt.Errorf("failed to commit file: %s", resp.Status)
	}

	return nil
}

// createPullRequest creates the actual PR
func (p *PRCreator) createPullRequest(ctx context.Context, owner, repo, head, base, title, body string) (*PRResponse, error) {
	url := fmt.Sprintf("%s/repos/%s/%s/pulls", p.config.BaseURL, owner, repo)

	reqBody := map[string]string{
		"title": title,
		"head":  head,
		"base":  base,
		"body":  body,
	}
	bodyBytes, _ := json.Marshal(reqBody)

	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewReader(bodyBytes))
	if err != nil {
		return nil, err
	}
	p.setHeaders(req)

	resp, err := p.httpClient.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		return nil, fmt.Errorf("failed to create PR: %s", resp.Status)
	}

	var prResp struct {
		Number    int       `json:"number"`
		URL       string    `json:"url"`
		HTMLURL   string    `json:"html_url"`
		State     string    `json:"state"`
		Title     string    `json:"title"`
		CreatedAt time.Time `json:"created_at"`
		Head      struct {
			Ref string `json:"ref"`
		} `json:"head"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&prResp); err != nil {
		return nil, err
	}

	return &PRResponse{
		Number:    prResp.Number,
		URL:       prResp.URL,
		HTMLURL:   prResp.HTMLURL,
		State:     prResp.State,
		Title:     prResp.Title,
		CreatedAt: prResp.CreatedAt,
		Branch:    prResp.Head.Ref,
	}, nil
}

// addLabels adds labels to a PR
func (p *PRCreator) addLabels(ctx context.Context, owner, repo string, prNumber int, labels []string) error {
	url := fmt.Sprintf("%s/repos/%s/%s/issues/%d/labels", p.config.BaseURL, owner, repo, prNumber)

	bodyBytes, _ := json.Marshal(labels)
	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewReader(bodyBytes))
	if err != nil {
		return err
	}
	p.setHeaders(req)

	resp, err := p.httpClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// setHeaders sets common headers for GitHub API requests
func (p *PRCreator) setHeaders(req *http.Request) {
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	req.Header.Set("Content-Type", "application/json")
	if p.config.GitHubToken != "" {
		req.Header.Set("Authorization", "token "+p.config.GitHubToken)
	}
}

// base64Encode encodes content to base64
func base64Encode(s string) string {
	// Simple base64 encoding
	const encodeStd = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	input := []byte(s)
	var buf bytes.Buffer

	for i := 0; i < len(input); i += 3 {
		var b uint32
		n := 0
		for j := 0; j < 3 && i+j < len(input); j++ {
			b = b<<8 | uint32(input[i+j])
			n++
		}
		b <<= uint(24 - n*8)

		for j := 0; j < n+1; j++ {
			buf.WriteByte(encodeStd[(b>>(18-j*6))&0x3F])
		}
		for j := n + 1; j < 4; j++ {
			buf.WriteByte('=')
		}
	}

	return buf.String()
}

// CreateMaintenancePRFromResults creates a PR from maintenance job results
func (p *PRCreator) CreateMaintenancePRFromResults(ctx context.Context, owner, repo, baseBranch string,
	removalResults []RemovalResult, regenResults []RegenerationResult) (*PRResponse, error) {

	var files []FileChange
	var results []PRResultItem

	// Process removal results
	for _, r := range removalResults {
		if r.Removed {
			files = append(files, FileChange{
				Path:   r.TestFile,
				Action: "delete",
			})
			results = append(results, PRResultItem{
				Type:    "removal",
				File:    r.TestFile,
				Success: true,
				Message: fmt.Sprintf("Removed test for %s", r.TargetID),
			})
		}
	}

	// Process regeneration results
	for _, r := range regenResults {
		if r.Success {
			files = append(files, FileChange{
				Path:   r.TestFile,
				Action: "update",
			})
			results = append(results, PRResultItem{
				Type:    "regeneration",
				File:    r.TestFile,
				Success: true,
				Message: fmt.Sprintf("Regenerated %d tests for %s", r.TestsCreated, r.TargetID),
			})
		}
	}

	if len(files) == 0 {
		return nil, fmt.Errorf("no changes to create PR for")
	}

	req := PRRequest{
		Owner:      owner,
		Repo:       repo,
		BaseBranch: baseBranch,
		Title:      fmt.Sprintf("chore(tests): maintenance update - %s", time.Now().Format("2006-01-02")),
		Files:      files,
		Results:    results,
	}

	return p.CreateMaintenancePR(ctx, req)
}
