// Package mockgen generates mock implementations of interfaces for testing
package mockgen

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"
	"unicode"

	"github.com/QTest-hq/qtest/pkg/model"
)

// Generator generates mock implementations of interfaces
type Generator struct {
	packageName string
}

// NewGenerator creates a new mock generator
func NewGenerator(packageName string) *Generator {
	return &Generator{
		packageName: packageName,
	}
}

// MockConfig configures mock generation
type MockConfig struct {
	// Package name for generated mocks (default: same as source + "_mock")
	PackageName string
	// Interface names to mock (empty means all)
	Interfaces []string
	// Generate recording capabilities
	WithRecording bool
	// Generate expectation assertions
	WithExpectations bool
}

// Interface represents an interface to be mocked
type Interface struct {
	Name    string
	Methods []Method
}

// Method represents a method in an interface
type Method struct {
	Name       string
	Parameters []Parameter
	Returns    []Parameter
}

// Parameter represents a method parameter or return value
type Parameter struct {
	Name string
	Type string
}

// GenerateFromModel generates mocks from a SystemModel
func (g *Generator) GenerateFromModel(model *model.SystemModel, config *MockConfig) (string, error) {
	interfaces := extractInterfaces(model, config)
	if len(interfaces) == 0 {
		return "", fmt.Errorf("no interfaces found to mock")
	}

	return g.generateMocks(interfaces, config)
}

// GenerateFromInterface generates a mock for a single interface definition
func (g *Generator) GenerateFromInterface(iface *Interface, config *MockConfig) (string, error) {
	if config == nil {
		config = &MockConfig{}
	}
	return g.generateMocks([]*Interface{iface}, config)
}

// extractInterfaces extracts interfaces from the SystemModel
func extractInterfaces(m *model.SystemModel, config *MockConfig) []*Interface {
	var interfaces []*Interface

	for _, typeDef := range m.Types {
		if typeDef.Kind != model.TypeKindInterface {
			continue
		}

		// Filter by interface name if specified
		if len(config.Interfaces) > 0 {
			found := false
			for _, name := range config.Interfaces {
				if typeDef.Name == name {
					found = true
					break
				}
			}
			if !found {
				continue
			}
		}

		// Build interface with methods
		iface := &Interface{
			Name:    typeDef.Name,
			Methods: extractMethods(m, typeDef),
		}
		interfaces = append(interfaces, iface)
	}

	return interfaces
}

// extractMethods gets methods for a type from the model
func extractMethods(m *model.SystemModel, typeDef model.TypeDef) []Method {
	var methods []Method

	for _, methodID := range typeDef.Methods {
		for _, fn := range m.Functions {
			if fn.ID == methodID {
				method := Method{
					Name:       fn.Name,
					Parameters: convertParameters(fn.Parameters),
					Returns:    convertParameters(fn.Returns),
				}
				methods = append(methods, method)
				break
			}
		}
	}

	return methods
}

// convertParameters converts model parameters to mock parameters
func convertParameters(params []model.Parameter) []Parameter {
	result := make([]Parameter, len(params))
	for i, p := range params {
		result[i] = Parameter{
			Name: p.Name,
			Type: p.Type,
		}
	}
	return result
}

// generateMocks generates the mock code
func (g *Generator) generateMocks(interfaces []*Interface, config *MockConfig) (string, error) {
	var buf bytes.Buffer

	pkgName := config.PackageName
	if pkgName == "" {
		pkgName = g.packageName + "_mock"
	}

	// Write package header
	buf.WriteString(fmt.Sprintf("// Code generated by QTest mockgen. DO NOT EDIT.\npackage %s\n\n", pkgName))

	// Write imports
	buf.WriteString("import (\n")
	buf.WriteString("\t\"sync\"\n")
	if config.WithExpectations {
		buf.WriteString("\t\"testing\"\n")
	}
	buf.WriteString(")\n\n")

	// Generate each mock
	for _, iface := range interfaces {
		mockCode, err := g.generateMock(iface, config)
		if err != nil {
			return "", err
		}
		buf.WriteString(mockCode)
		buf.WriteString("\n")
	}

	return buf.String(), nil
}

// generateMock generates a mock for a single interface
func (g *Generator) generateMock(iface *Interface, config *MockConfig) (string, error) {
	tmpl, err := template.New("mock").Funcs(template.FuncMap{
		"unexport":     unexport,
		"formatParams": formatParams,
		"formatReturn": formatReturn,
		"paramNames":   paramNames,
		"zeroValues":   zeroValues,
	}).Parse(mockTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	data := struct {
		Interface        *Interface
		WithRecording    bool
		WithExpectations bool
	}{
		Interface:        iface,
		WithRecording:    config.WithRecording,
		WithExpectations: config.WithExpectations,
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// unexport converts a name to unexported (lowercase first letter)
func unexport(name string) string {
	if name == "" {
		return name
	}
	runes := []rune(name)
	runes[0] = unicode.ToLower(runes[0])
	return string(runes)
}

// formatParams formats parameters for a method signature
func formatParams(params []Parameter) string {
	if len(params) == 0 {
		return ""
	}

	var parts []string
	for _, p := range params {
		if p.Name != "" {
			parts = append(parts, fmt.Sprintf("%s %s", p.Name, p.Type))
		} else {
			parts = append(parts, p.Type)
		}
	}
	return strings.Join(parts, ", ")
}

// formatReturn formats return types
func formatReturn(returns []Parameter) string {
	if len(returns) == 0 {
		return ""
	}

	var types []string
	for _, r := range returns {
		types = append(types, r.Type)
	}

	if len(types) == 1 {
		return types[0]
	}
	return "(" + strings.Join(types, ", ") + ")"
}

// paramNames returns just the parameter names
func paramNames(params []Parameter) string {
	if len(params) == 0 {
		return ""
	}

	var names []string
	for i, p := range params {
		if p.Name != "" {
			names = append(names, p.Name)
		} else {
			names = append(names, fmt.Sprintf("arg%d", i))
		}
	}
	return strings.Join(names, ", ")
}

// zeroValues returns zero values for return types
func zeroValues(returns []Parameter) string {
	if len(returns) == 0 {
		return ""
	}

	var values []string
	for _, r := range returns {
		values = append(values, zeroValue(r.Type))
	}
	return strings.Join(values, ", ")
}

// zeroValue returns the zero value for a type
func zeroValue(typeName string) string {
	typeName = strings.TrimPrefix(typeName, "*")

	switch typeName {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64", "byte", "rune":
		return "0"
	case "bool":
		return "false"
	case "string":
		return `""`
	case "error":
		return "nil"
	default:
		if strings.HasPrefix(typeName, "[]") || strings.HasPrefix(typeName, "map[") {
			return "nil"
		}
		return "nil"
	}
}

const mockTemplate = `// Mock{{.Interface.Name}} is a mock implementation of {{.Interface.Name}}
type Mock{{.Interface.Name}} struct {
	mu sync.RWMutex
{{- range .Interface.Methods}}
	{{unexport .Name}}Func func({{formatParams .Parameters}}) {{formatReturn .Returns}}
{{- end}}
{{- if $.WithRecording}}

	// Call recording
	calls struct {
{{- range .Interface.Methods}}
		{{.Name}} []struct {
{{- range .Parameters}}
			{{.Name}} {{.Type}}
{{- end}}
		}
{{- end}}
	}
{{- end}}
}

// NewMock{{.Interface.Name}} creates a new mock
func NewMock{{.Interface.Name}}() *Mock{{.Interface.Name}} {
	return &Mock{{.Interface.Name}}{}
}
{{range .Interface.Methods}}
// {{.Name}} implements {{$.Interface.Name}}.{{.Name}}
func (m *Mock{{$.Interface.Name}}) {{.Name}}({{formatParams .Parameters}}) {{formatReturn .Returns}} {
	m.mu.RLock()
	defer m.mu.RUnlock()
{{- if $.WithRecording}}

	// Record call
	m.calls.{{.Name}} = append(m.calls.{{.Name}}, struct {
{{- range .Parameters}}
		{{.Name}} {{.Type}}
{{- end}}
	}{ {{- paramNames .Parameters -}} })
{{- end}}

	if m.{{unexport .Name}}Func != nil {
		return m.{{unexport .Name}}Func({{paramNames .Parameters}})
	}
{{if .Returns}}	return {{zeroValues .Returns}}{{end}}
}
{{end}}
{{- if .WithRecording}}
{{- range .Interface.Methods}}
// {{.Name}}Calls returns recorded calls to {{.Name}}
func (m *Mock{{$.Interface.Name}}) {{.Name}}Calls() []struct {
{{- range .Parameters}}
	{{.Name}} {{.Type}}
{{- end}}
} {
	m.mu.RLock()
	defer m.mu.RUnlock()
	return m.calls.{{.Name}}
}
{{end}}
{{- end}}
`
