// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: playwright.proto

package playwright

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PlaywrightService_CreateSession_FullMethodName         = "/playwright.PlaywrightService/CreateSession"
	PlaywrightService_DestroySession_FullMethodName        = "/playwright.PlaywrightService/DestroySession"
	PlaywrightService_GetSessionStatus_FullMethodName      = "/playwright.PlaywrightService/GetSessionStatus"
	PlaywrightService_Navigate_FullMethodName              = "/playwright.PlaywrightService/Navigate"
	PlaywrightService_Click_FullMethodName                 = "/playwright.PlaywrightService/Click"
	PlaywrightService_Fill_FullMethodName                  = "/playwright.PlaywrightService/Fill"
	PlaywrightService_Select_FullMethodName                = "/playwright.PlaywrightService/Select"
	PlaywrightService_Press_FullMethodName                 = "/playwright.PlaywrightService/Press"
	PlaywrightService_Hover_FullMethodName                 = "/playwright.PlaywrightService/Hover"
	PlaywrightService_WaitForSelector_FullMethodName       = "/playwright.PlaywrightService/WaitForSelector"
	PlaywrightService_WaitForNavigation_FullMethodName     = "/playwright.PlaywrightService/WaitForNavigation"
	PlaywrightService_GetDOMSnapshot_FullMethodName        = "/playwright.PlaywrightService/GetDOMSnapshot"
	PlaywrightService_GetElement_FullMethodName            = "/playwright.PlaywrightService/GetElement"
	PlaywrightService_GetElements_FullMethodName           = "/playwright.PlaywrightService/GetElements"
	PlaywrightService_EvaluateScript_FullMethodName        = "/playwright.PlaywrightService/EvaluateScript"
	PlaywrightService_TakeScreenshot_FullMethodName        = "/playwright.PlaywrightService/TakeScreenshot"
	PlaywrightService_TakeElementScreenshot_FullMethodName = "/playwright.PlaywrightService/TakeElementScreenshot"
	PlaywrightService_StartNetworkCapture_FullMethodName   = "/playwright.PlaywrightService/StartNetworkCapture"
	PlaywrightService_StopNetworkCapture_FullMethodName    = "/playwright.PlaywrightService/StopNetworkCapture"
	PlaywrightService_GetCapturedRequests_FullMethodName   = "/playwright.PlaywrightService/GetCapturedRequests"
	PlaywrightService_SetRequestInterceptor_FullMethodName = "/playwright.PlaywrightService/SetRequestInterceptor"
	PlaywrightService_GetPageLinks_FullMethodName          = "/playwright.PlaywrightService/GetPageLinks"
	PlaywrightService_GetPageForms_FullMethodName          = "/playwright.PlaywrightService/GetPageForms"
)

// PlaywrightServiceClient is the client API for PlaywrightService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PlaywrightService provides browser automation capabilities
type PlaywrightServiceClient interface {
	// Session management
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error)
	GetSessionStatus(ctx context.Context, in *GetSessionStatusRequest, opts ...grpc.CallOption) (*GetSessionStatusResponse, error)
	// Page navigation
	Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error)
	Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ClickResponse, error)
	Fill(ctx context.Context, in *FillRequest, opts ...grpc.CallOption) (*FillResponse, error)
	Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error)
	Press(ctx context.Context, in *PressRequest, opts ...grpc.CallOption) (*PressResponse, error)
	Hover(ctx context.Context, in *HoverRequest, opts ...grpc.CallOption) (*HoverResponse, error)
	WaitForSelector(ctx context.Context, in *WaitForSelectorRequest, opts ...grpc.CallOption) (*WaitForSelectorResponse, error)
	WaitForNavigation(ctx context.Context, in *WaitForNavigationRequest, opts ...grpc.CallOption) (*WaitForNavigationResponse, error)
	// DOM operations
	GetDOMSnapshot(ctx context.Context, in *GetDOMSnapshotRequest, opts ...grpc.CallOption) (*GetDOMSnapshotResponse, error)
	GetElement(ctx context.Context, in *GetElementRequest, opts ...grpc.CallOption) (*GetElementResponse, error)
	GetElements(ctx context.Context, in *GetElementsRequest, opts ...grpc.CallOption) (*GetElementsResponse, error)
	EvaluateScript(ctx context.Context, in *EvaluateScriptRequest, opts ...grpc.CallOption) (*EvaluateScriptResponse, error)
	// Screenshots
	TakeScreenshot(ctx context.Context, in *TakeScreenshotRequest, opts ...grpc.CallOption) (*TakeScreenshotResponse, error)
	TakeElementScreenshot(ctx context.Context, in *TakeElementScreenshotRequest, opts ...grpc.CallOption) (*TakeElementScreenshotResponse, error)
	// Network interception
	StartNetworkCapture(ctx context.Context, in *StartNetworkCaptureRequest, opts ...grpc.CallOption) (*StartNetworkCaptureResponse, error)
	StopNetworkCapture(ctx context.Context, in *StopNetworkCaptureRequest, opts ...grpc.CallOption) (*StopNetworkCaptureResponse, error)
	GetCapturedRequests(ctx context.Context, in *GetCapturedRequestsRequest, opts ...grpc.CallOption) (*GetCapturedRequestsResponse, error)
	SetRequestInterceptor(ctx context.Context, in *SetRequestInterceptorRequest, opts ...grpc.CallOption) (*SetRequestInterceptorResponse, error)
	// Crawler support
	GetPageLinks(ctx context.Context, in *GetPageLinksRequest, opts ...grpc.CallOption) (*GetPageLinksResponse, error)
	GetPageForms(ctx context.Context, in *GetPageFormsRequest, opts ...grpc.CallOption) (*GetPageFormsResponse, error)
}

type playwrightServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlaywrightServiceClient(cc grpc.ClientConnInterface) PlaywrightServiceClient {
	return &playwrightServiceClient{cc}
}

func (c *playwrightServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) DestroySession(ctx context.Context, in *DestroySessionRequest, opts ...grpc.CallOption) (*DestroySessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroySessionResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) GetSessionStatus(ctx context.Context, in *GetSessionStatusRequest, opts ...grpc.CallOption) (*GetSessionStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionStatusResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_GetSessionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) Navigate(ctx context.Context, in *NavigateRequest, opts ...grpc.CallOption) (*NavigateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NavigateResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_Navigate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ClickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClickResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_Click_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) Fill(ctx context.Context, in *FillRequest, opts ...grpc.CallOption) (*FillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FillResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_Fill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) Select(ctx context.Context, in *SelectRequest, opts ...grpc.CallOption) (*SelectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_Select_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) Press(ctx context.Context, in *PressRequest, opts ...grpc.CallOption) (*PressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PressResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_Press_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) Hover(ctx context.Context, in *HoverRequest, opts ...grpc.CallOption) (*HoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HoverResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_Hover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) WaitForSelector(ctx context.Context, in *WaitForSelectorRequest, opts ...grpc.CallOption) (*WaitForSelectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForSelectorResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_WaitForSelector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) WaitForNavigation(ctx context.Context, in *WaitForNavigationRequest, opts ...grpc.CallOption) (*WaitForNavigationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForNavigationResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_WaitForNavigation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) GetDOMSnapshot(ctx context.Context, in *GetDOMSnapshotRequest, opts ...grpc.CallOption) (*GetDOMSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDOMSnapshotResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_GetDOMSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) GetElement(ctx context.Context, in *GetElementRequest, opts ...grpc.CallOption) (*GetElementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetElementResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_GetElement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) GetElements(ctx context.Context, in *GetElementsRequest, opts ...grpc.CallOption) (*GetElementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetElementsResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_GetElements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) EvaluateScript(ctx context.Context, in *EvaluateScriptRequest, opts ...grpc.CallOption) (*EvaluateScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateScriptResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_EvaluateScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) TakeScreenshot(ctx context.Context, in *TakeScreenshotRequest, opts ...grpc.CallOption) (*TakeScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeScreenshotResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_TakeScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) TakeElementScreenshot(ctx context.Context, in *TakeElementScreenshotRequest, opts ...grpc.CallOption) (*TakeElementScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeElementScreenshotResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_TakeElementScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) StartNetworkCapture(ctx context.Context, in *StartNetworkCaptureRequest, opts ...grpc.CallOption) (*StartNetworkCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartNetworkCaptureResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_StartNetworkCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) StopNetworkCapture(ctx context.Context, in *StopNetworkCaptureRequest, opts ...grpc.CallOption) (*StopNetworkCaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopNetworkCaptureResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_StopNetworkCapture_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) GetCapturedRequests(ctx context.Context, in *GetCapturedRequestsRequest, opts ...grpc.CallOption) (*GetCapturedRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCapturedRequestsResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_GetCapturedRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) SetRequestInterceptor(ctx context.Context, in *SetRequestInterceptorRequest, opts ...grpc.CallOption) (*SetRequestInterceptorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRequestInterceptorResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_SetRequestInterceptor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) GetPageLinks(ctx context.Context, in *GetPageLinksRequest, opts ...grpc.CallOption) (*GetPageLinksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPageLinksResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_GetPageLinks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *playwrightServiceClient) GetPageForms(ctx context.Context, in *GetPageFormsRequest, opts ...grpc.CallOption) (*GetPageFormsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPageFormsResponse)
	err := c.cc.Invoke(ctx, PlaywrightService_GetPageForms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaywrightServiceServer is the server API for PlaywrightService service.
// All implementations must embed UnimplementedPlaywrightServiceServer
// for forward compatibility.
//
// PlaywrightService provides browser automation capabilities
type PlaywrightServiceServer interface {
	// Session management
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error)
	GetSessionStatus(context.Context, *GetSessionStatusRequest) (*GetSessionStatusResponse, error)
	// Page navigation
	Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error)
	Click(context.Context, *ClickRequest) (*ClickResponse, error)
	Fill(context.Context, *FillRequest) (*FillResponse, error)
	Select(context.Context, *SelectRequest) (*SelectResponse, error)
	Press(context.Context, *PressRequest) (*PressResponse, error)
	Hover(context.Context, *HoverRequest) (*HoverResponse, error)
	WaitForSelector(context.Context, *WaitForSelectorRequest) (*WaitForSelectorResponse, error)
	WaitForNavigation(context.Context, *WaitForNavigationRequest) (*WaitForNavigationResponse, error)
	// DOM operations
	GetDOMSnapshot(context.Context, *GetDOMSnapshotRequest) (*GetDOMSnapshotResponse, error)
	GetElement(context.Context, *GetElementRequest) (*GetElementResponse, error)
	GetElements(context.Context, *GetElementsRequest) (*GetElementsResponse, error)
	EvaluateScript(context.Context, *EvaluateScriptRequest) (*EvaluateScriptResponse, error)
	// Screenshots
	TakeScreenshot(context.Context, *TakeScreenshotRequest) (*TakeScreenshotResponse, error)
	TakeElementScreenshot(context.Context, *TakeElementScreenshotRequest) (*TakeElementScreenshotResponse, error)
	// Network interception
	StartNetworkCapture(context.Context, *StartNetworkCaptureRequest) (*StartNetworkCaptureResponse, error)
	StopNetworkCapture(context.Context, *StopNetworkCaptureRequest) (*StopNetworkCaptureResponse, error)
	GetCapturedRequests(context.Context, *GetCapturedRequestsRequest) (*GetCapturedRequestsResponse, error)
	SetRequestInterceptor(context.Context, *SetRequestInterceptorRequest) (*SetRequestInterceptorResponse, error)
	// Crawler support
	GetPageLinks(context.Context, *GetPageLinksRequest) (*GetPageLinksResponse, error)
	GetPageForms(context.Context, *GetPageFormsRequest) (*GetPageFormsResponse, error)
	mustEmbedUnimplementedPlaywrightServiceServer()
}

// UnimplementedPlaywrightServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlaywrightServiceServer struct{}

func (UnimplementedPlaywrightServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedPlaywrightServiceServer) DestroySession(context.Context, *DestroySessionRequest) (*DestroySessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedPlaywrightServiceServer) GetSessionStatus(context.Context, *GetSessionStatusRequest) (*GetSessionStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionStatus not implemented")
}
func (UnimplementedPlaywrightServiceServer) Navigate(context.Context, *NavigateRequest) (*NavigateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Navigate not implemented")
}
func (UnimplementedPlaywrightServiceServer) Click(context.Context, *ClickRequest) (*ClickResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Click not implemented")
}
func (UnimplementedPlaywrightServiceServer) Fill(context.Context, *FillRequest) (*FillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fill not implemented")
}
func (UnimplementedPlaywrightServiceServer) Select(context.Context, *SelectRequest) (*SelectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Select not implemented")
}
func (UnimplementedPlaywrightServiceServer) Press(context.Context, *PressRequest) (*PressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Press not implemented")
}
func (UnimplementedPlaywrightServiceServer) Hover(context.Context, *HoverRequest) (*HoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hover not implemented")
}
func (UnimplementedPlaywrightServiceServer) WaitForSelector(context.Context, *WaitForSelectorRequest) (*WaitForSelectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForSelector not implemented")
}
func (UnimplementedPlaywrightServiceServer) WaitForNavigation(context.Context, *WaitForNavigationRequest) (*WaitForNavigationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitForNavigation not implemented")
}
func (UnimplementedPlaywrightServiceServer) GetDOMSnapshot(context.Context, *GetDOMSnapshotRequest) (*GetDOMSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDOMSnapshot not implemented")
}
func (UnimplementedPlaywrightServiceServer) GetElement(context.Context, *GetElementRequest) (*GetElementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetElement not implemented")
}
func (UnimplementedPlaywrightServiceServer) GetElements(context.Context, *GetElementsRequest) (*GetElementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetElements not implemented")
}
func (UnimplementedPlaywrightServiceServer) EvaluateScript(context.Context, *EvaluateScriptRequest) (*EvaluateScriptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateScript not implemented")
}
func (UnimplementedPlaywrightServiceServer) TakeScreenshot(context.Context, *TakeScreenshotRequest) (*TakeScreenshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeScreenshot not implemented")
}
func (UnimplementedPlaywrightServiceServer) TakeElementScreenshot(context.Context, *TakeElementScreenshotRequest) (*TakeElementScreenshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeElementScreenshot not implemented")
}
func (UnimplementedPlaywrightServiceServer) StartNetworkCapture(context.Context, *StartNetworkCaptureRequest) (*StartNetworkCaptureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartNetworkCapture not implemented")
}
func (UnimplementedPlaywrightServiceServer) StopNetworkCapture(context.Context, *StopNetworkCaptureRequest) (*StopNetworkCaptureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopNetworkCapture not implemented")
}
func (UnimplementedPlaywrightServiceServer) GetCapturedRequests(context.Context, *GetCapturedRequestsRequest) (*GetCapturedRequestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCapturedRequests not implemented")
}
func (UnimplementedPlaywrightServiceServer) SetRequestInterceptor(context.Context, *SetRequestInterceptorRequest) (*SetRequestInterceptorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRequestInterceptor not implemented")
}
func (UnimplementedPlaywrightServiceServer) GetPageLinks(context.Context, *GetPageLinksRequest) (*GetPageLinksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPageLinks not implemented")
}
func (UnimplementedPlaywrightServiceServer) GetPageForms(context.Context, *GetPageFormsRequest) (*GetPageFormsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPageForms not implemented")
}
func (UnimplementedPlaywrightServiceServer) mustEmbedUnimplementedPlaywrightServiceServer() {}
func (UnimplementedPlaywrightServiceServer) testEmbeddedByValue()                           {}

// UnsafePlaywrightServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlaywrightServiceServer will
// result in compilation errors.
type UnsafePlaywrightServiceServer interface {
	mustEmbedUnimplementedPlaywrightServiceServer()
}

func RegisterPlaywrightServiceServer(s grpc.ServiceRegistrar, srv PlaywrightServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlaywrightServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlaywrightService_ServiceDesc, srv)
}

func _PlaywrightService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroySessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).DestroySession(ctx, req.(*DestroySessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_GetSessionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).GetSessionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_GetSessionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).GetSessionStatus(ctx, req.(*GetSessionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_Navigate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NavigateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).Navigate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_Navigate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).Navigate(ctx, req.(*NavigateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_Click_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).Click(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_Click_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).Click(ctx, req.(*ClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_Fill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).Fill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_Fill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).Fill(ctx, req.(*FillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_Select_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).Select(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_Select_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).Select(ctx, req.(*SelectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_Press_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).Press(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_Press_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).Press(ctx, req.(*PressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_Hover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).Hover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_Hover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).Hover(ctx, req.(*HoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_WaitForSelector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForSelectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).WaitForSelector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_WaitForSelector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).WaitForSelector(ctx, req.(*WaitForSelectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_WaitForNavigation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForNavigationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).WaitForNavigation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_WaitForNavigation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).WaitForNavigation(ctx, req.(*WaitForNavigationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_GetDOMSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDOMSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).GetDOMSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_GetDOMSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).GetDOMSnapshot(ctx, req.(*GetDOMSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_GetElement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetElementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).GetElement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_GetElement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).GetElement(ctx, req.(*GetElementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_GetElements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetElementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).GetElements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_GetElements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).GetElements(ctx, req.(*GetElementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_EvaluateScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).EvaluateScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_EvaluateScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).EvaluateScript(ctx, req.(*EvaluateScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_TakeScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).TakeScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_TakeScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).TakeScreenshot(ctx, req.(*TakeScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_TakeElementScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeElementScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).TakeElementScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_TakeElementScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).TakeElementScreenshot(ctx, req.(*TakeElementScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_StartNetworkCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartNetworkCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).StartNetworkCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_StartNetworkCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).StartNetworkCapture(ctx, req.(*StartNetworkCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_StopNetworkCapture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopNetworkCaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).StopNetworkCapture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_StopNetworkCapture_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).StopNetworkCapture(ctx, req.(*StopNetworkCaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_GetCapturedRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCapturedRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).GetCapturedRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_GetCapturedRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).GetCapturedRequests(ctx, req.(*GetCapturedRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_SetRequestInterceptor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequestInterceptorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).SetRequestInterceptor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_SetRequestInterceptor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).SetRequestInterceptor(ctx, req.(*SetRequestInterceptorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_GetPageLinks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageLinksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).GetPageLinks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_GetPageLinks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).GetPageLinks(ctx, req.(*GetPageLinksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlaywrightService_GetPageForms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPageFormsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaywrightServiceServer).GetPageForms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlaywrightService_GetPageForms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaywrightServiceServer).GetPageForms(ctx, req.(*GetPageFormsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlaywrightService_ServiceDesc is the grpc.ServiceDesc for PlaywrightService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlaywrightService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "playwright.PlaywrightService",
	HandlerType: (*PlaywrightServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _PlaywrightService_CreateSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _PlaywrightService_DestroySession_Handler,
		},
		{
			MethodName: "GetSessionStatus",
			Handler:    _PlaywrightService_GetSessionStatus_Handler,
		},
		{
			MethodName: "Navigate",
			Handler:    _PlaywrightService_Navigate_Handler,
		},
		{
			MethodName: "Click",
			Handler:    _PlaywrightService_Click_Handler,
		},
		{
			MethodName: "Fill",
			Handler:    _PlaywrightService_Fill_Handler,
		},
		{
			MethodName: "Select",
			Handler:    _PlaywrightService_Select_Handler,
		},
		{
			MethodName: "Press",
			Handler:    _PlaywrightService_Press_Handler,
		},
		{
			MethodName: "Hover",
			Handler:    _PlaywrightService_Hover_Handler,
		},
		{
			MethodName: "WaitForSelector",
			Handler:    _PlaywrightService_WaitForSelector_Handler,
		},
		{
			MethodName: "WaitForNavigation",
			Handler:    _PlaywrightService_WaitForNavigation_Handler,
		},
		{
			MethodName: "GetDOMSnapshot",
			Handler:    _PlaywrightService_GetDOMSnapshot_Handler,
		},
		{
			MethodName: "GetElement",
			Handler:    _PlaywrightService_GetElement_Handler,
		},
		{
			MethodName: "GetElements",
			Handler:    _PlaywrightService_GetElements_Handler,
		},
		{
			MethodName: "EvaluateScript",
			Handler:    _PlaywrightService_EvaluateScript_Handler,
		},
		{
			MethodName: "TakeScreenshot",
			Handler:    _PlaywrightService_TakeScreenshot_Handler,
		},
		{
			MethodName: "TakeElementScreenshot",
			Handler:    _PlaywrightService_TakeElementScreenshot_Handler,
		},
		{
			MethodName: "StartNetworkCapture",
			Handler:    _PlaywrightService_StartNetworkCapture_Handler,
		},
		{
			MethodName: "StopNetworkCapture",
			Handler:    _PlaywrightService_StopNetworkCapture_Handler,
		},
		{
			MethodName: "GetCapturedRequests",
			Handler:    _PlaywrightService_GetCapturedRequests_Handler,
		},
		{
			MethodName: "SetRequestInterceptor",
			Handler:    _PlaywrightService_SetRequestInterceptor_Handler,
		},
		{
			MethodName: "GetPageLinks",
			Handler:    _PlaywrightService_GetPageLinks_Handler,
		},
		{
			MethodName: "GetPageForms",
			Handler:    _PlaywrightService_GetPageForms_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playwright.proto",
}
