package metrics

import "github.com/prometheus/client_golang/prometheus"

var (
	// JobsCreatedTotal counts jobs created by type
	JobsCreatedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "jobs",
			Name:      "created_total",
			Help:      "Total number of jobs created, labeled by job type",
		},
		[]string{"type"},
	)

	// JobsCompletedTotal counts completed jobs by type and status
	JobsCompletedTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "jobs",
			Name:      "completed_total",
			Help:      "Total number of jobs completed, labeled by type and final status",
		},
		[]string{"type", "status"},
	)

	// JobsInProgress tracks jobs currently being processed by type and worker
	JobsInProgress = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: Namespace,
			Subsystem: "jobs",
			Name:      "in_progress",
			Help:      "Number of jobs currently being processed, labeled by type and worker ID",
		},
		[]string{"type", "worker_id"},
	)

	// JobDuration measures job processing duration by type
	JobDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: Namespace,
			Subsystem: "jobs",
			Name:      "duration_seconds",
			Help:      "Job processing duration in seconds, labeled by job type",
			Buckets:   jobDurationBuckets(),
		},
		[]string{"type"},
	)

	// JobRetries counts job retry attempts by type
	JobRetries = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "jobs",
			Name:      "retries_total",
			Help:      "Total number of job retry attempts, labeled by job type",
		},
		[]string{"type"},
	)

	// JobQueueDepth tracks the number of jobs in queue by status
	JobQueueDepth = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: Namespace,
			Subsystem: "jobs",
			Name:      "queue_depth",
			Help:      "Number of jobs in queue, labeled by status",
		},
		[]string{"status"},
	)

	// TestsGeneratedTotal counts the total number of tests generated
	TestsGeneratedTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "jobs",
			Name:      "tests_generated_total",
			Help:      "Total number of test cases generated by the system",
		},
	)

	// MutantsKilledTotal counts the total number of mutants killed
	MutantsKilledTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "jobs",
			Name:      "mutants_killed_total",
			Help:      "Total number of mutants killed during mutation testing",
		},
	)

	// MutantsSurvivedTotal counts the total number of mutants that survived
	MutantsSurvivedTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "jobs",
			Name:      "mutants_survived_total",
			Help:      "Total number of mutants that survived mutation testing",
		},
	)
)

// RegisterJobMetrics registers all job-related metrics with the registry
func RegisterJobMetrics() {
	Registry.MustRegister(
		JobsCreatedTotal,
		JobsCompletedTotal,
		JobsInProgress,
		JobDuration,
		JobRetries,
		JobQueueDepth,
		TestsGeneratedTotal,
		MutantsKilledTotal,
		MutantsSurvivedTotal,
	)
}
