package metrics

import "github.com/prometheus/client_golang/prometheus"

var (
	// LLMRequestsTotal counts LLM requests by provider, model, tier, and status
	LLMRequestsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "llm",
			Name:      "requests_total",
			Help:      "Total number of LLM requests, labeled by provider, model, tier, and status",
		},
		[]string{"provider", "model", "tier", "status"},
	)

	// LLMRequestDuration measures LLM request latency by provider and tier
	LLMRequestDuration = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: Namespace,
			Subsystem: "llm",
			Name:      "request_duration_seconds",
			Help:      "LLM request duration in seconds, labeled by provider and tier",
			Buckets:   []float64{1, 2, 5, 10, 20, 30, 60, 120, 300},
		},
		[]string{"provider", "tier"},
	)

	// LLMTokensInputTotal counts input tokens consumed by provider and model
	LLMTokensInputTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "llm",
			Name:      "tokens_input_total",
			Help:      "Total number of input tokens consumed, labeled by provider and model",
		},
		[]string{"provider", "model"},
	)

	// LLMTokensOutputTotal counts output tokens generated by provider and model
	LLMTokensOutputTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "llm",
			Name:      "tokens_output_total",
			Help:      "Total number of output tokens generated, labeled by provider and model",
		},
		[]string{"provider", "model"},
	)

	// LLMCacheHits counts cache hits for LLM requests
	LLMCacheHits = prometheus.NewCounter(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "llm",
			Name:      "cache_hits_total",
			Help:      "Total number of LLM cache hits",
		},
	)

	// LLMCacheMisses counts cache misses for LLM requests
	LLMCacheMisses = prometheus.NewCounter(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "llm",
			Name:      "cache_misses_total",
			Help:      "Total number of LLM cache misses",
		},
	)

	// LLMErrors counts LLM errors by provider and error type
	LLMErrors = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "llm",
			Name:      "errors_total",
			Help:      "Total number of LLM errors, labeled by provider and error type",
		},
		[]string{"provider", "error_type"},
	)

	// LLMQueuedRequests tracks the number of LLM requests waiting in queue
	LLMQueuedRequests = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: Namespace,
			Subsystem: "llm",
			Name:      "queued_requests",
			Help:      "Number of LLM requests currently queued, labeled by tier",
		},
		[]string{"tier"},
	)

	// LLMCostTotal tracks estimated cost by provider and model (in USD cents)
	LLMCostTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: Namespace,
			Subsystem: "llm",
			Name:      "cost_cents_total",
			Help:      "Estimated total cost in USD cents, labeled by provider and model",
		},
		[]string{"provider", "model"},
	)
)

// RegisterLLMMetrics registers all LLM-related metrics with the registry
func RegisterLLMMetrics() {
	Registry.MustRegister(
		LLMRequestsTotal,
		LLMRequestDuration,
		LLMTokensInputTotal,
		LLMTokensOutputTotal,
		LLMCacheHits,
		LLMCacheMisses,
		LLMErrors,
		LLMQueuedRequests,
		LLMCostTotal,
	)
}
